//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ISO20022.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ISO20022.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to the file {0} does not contain a valid XSD and has been ignored.
        /// </summary>
        internal static string ErrorInvalidXSDFile {
            get {
                return ResourceManager.GetString("ErrorInvalidXSDFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to the resource {0} does not contain a valid XSD and has been ignored.
        /// </summary>
        internal static string ErrorInvalidXSDResource {
            get {
                return ResourceManager.GetString("ErrorInvalidXSDResource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to no data to deserialize.
        /// </summary>
        internal static string ErrorNoDataToDeserialize {
            get {
                return ResourceManager.GetString("ErrorNoDataToDeserialize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to no data to serialize.
        /// </summary>
        internal static string ErrorNoDataToSerialize {
            get {
                return ResourceManager.GetString("ErrorNoDataToSerialize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to no document of class {0} has been created.
        /// </summary>
        internal static string ExceptionMessageNoDocumentCreated {
            get {
                return ResourceManager.GetString("ExceptionMessageNoDocumentCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to no generic constructor found for class {0}.
        /// </summary>
        internal static string ExceptionMessageNoGenericConstructor {
            get {
                return ResourceManager.GetString("ExceptionMessageNoGenericConstructor", resourceCulture);
            }
        }
    }
}
